### PR TITLE
Issue #2: Fix the user-agent to be based on the user's email address

### PR DESCRIPTION
**Pull request by nickp10**
Fixing issue #2

### CODE REVIEW

**Comment by nickp10** [comment]
No worries, I have reverted the string templating.

**Comment by roccomuso** [comment]
Thanks!

**Comment by caillou** [comment]
I just read the [documentation](https://www.noip.com/integrate/request) and noticed the following:

> Your user agent should be in the following format
> `User-Agent: NameOfUpdateProgram/VersionNumber maintainercontact@domain.com`

The email address should be the one of the **client maintainer**, not the one of the user.

While this provably isn't too important, I would vote to revert that change.

@roccomuso WDYT?

**Comment by roccomuso** [comment]
Is that the reason behind https://github.com/roccomuso/no-ip/pull/5?

**Comment by caillou** [comment]
@roccomuso this has nothing to do with #5, I just noticed the discrepancy with the `noip` documentation when reading the code.

**Comment by roccomuso** [comment]
Let's leave it this way, otherwise I can't imagine a suitable email for this.

**Pull request merged**
